version: '3'

volumes:
  mongo-volume:

services:
  web:
    build:
      context: .
    image: mouseton/springblog
    restart: always
    depends_on:
      - mongo
    ports:
      - 8080:8080

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

  mongo:
    image: mongo
    container_name: mongodb-container
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongo-volume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
