version: '3'

volumes:
  mongo-volume:

services:
  web:
    #    image: docker-test
    build:
      context: .
    restart: always
    depends_on:
      - mongo
    #    links:
    #      - mongo:mongo
    #    volumes:
    #    - data-volume:application/avatars
    ports:
      - 8080:8080
    environment:
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}

  mongo:
    image: mongo
    container_name: mongodb-container
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongo-volume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
